pipeline:
  name: SemanticSegmentationPipeline
  encoder:
    name: get_encoder
    params:
      name: efficientnet-b0
      in_channels: 3
      depth: 5
      weights: imagenet
  decoder:
    name: UnetDecoder
    params:
      decoder_channels: [256, 128, 64, 32, 16]
      n_blocks: 5
      use_batchnorm: True
      attention_type: null
      center: False
  segmentation_head:
    name: SegmentationHead
    params:
      conv2d:
        name: Conv2d
        params:
          in_channels: 16
          out_channels: 1
          kernel_size: 3
          padding: 1
      upsampling:
        name: UpsamplingBilinear2d
        params:
          scale_factor: 1
      activation:
        name: Activation
        params:
          name: null
          params:
